
ContextPath: http://localhost:8500

spring:
  application:
    name: Cinevestor-website
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      


management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
